# Generated by Django 5.1.7 on 2025-04-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0004_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
    ]
