# Generated by Django 5.1.7 on 2025-04-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0005_customuser_phone_no_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RavenshawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('event_location', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
