# Generated by Django 5.1.7 on 2025-04-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0011_jobpost_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravenshawevent',
            name='event_img',
            field=models.ImageField(default='#', upload_to='event_images/'),
        ),
    ]
