# Generated by Django 5.1.7 on 2025-04-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0012_ravenshawevent_event_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
