# Generated by Django 5.1.7 on 2025-03-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='default_pf.png', upload_to='profile_images/'),
        ),
    ]
