# Generated by Django 5.1.7 on 2025-04-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0002_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='IMG-01.jpg', upload_to='profile_images/'),
        ),
    ]
