# Generated by Django 5.1.7 on 2025-04-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0008_alumniconnection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniConnection',
        ),
    ]
