# Generated by Django 5.1.7 on 2025-04-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0015_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
