# Generated by Django 5.1.7 on 2025-04-17 09:38

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0019_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='default_pf_faq5zi.png', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_images/'),
        ),
    ]
