# Generated by Django 5.1.7 on 2025-04-17 10:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0020_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestImage',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/do7vm8vz3/image/upload/v1744881837/default_pf_faq5zi.png', max_length=255, null=True, verbose_name='profile_images'),
        ),
    ]
