# Generated by Django 5.1.7 on 2025-04-17 15:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0021_delete_testimage_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravenshawevent',
            name='event_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/do7vm8vz3/image/upload/v1744900889/WhatsApp_Image_2025-04-17_at_8.03.06_PM_ie50i3.jpg', max_length=255, null=True, verbose_name='event_images'),
        ),
    ]
