# Generated by Django 5.1.7 on 2025-04-18 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0022_alter_ravenshawevent_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(limit_value=300, message='Description cannot exceed 300 characters')]),
        ),
        migrations.AlterField(
            model_name='ravenshawevent',
            name='event_description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(limit_value=300, message='Description cannot exceed 300 characters')]),
        ),
    ]
