# Generated by Django 5.1.7 on 2025-12-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0023_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
